// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_patient_zero = "CgkIiYq2_50FEAIQAQ"; // <GPGSID>
        public const string achievement_landfall = "CgkIiYq2_50FEAIQAg"; // <GPGSID>
        public const string achievement_mutation = "CgkIiYq2_50FEAIQAw"; // <GPGSID>
        public const string achievement_the_hornets_nest = "CgkIiYq2_50FEAIQCA"; // <GPGSID>
        public const string achievement_sting_like_a_bee = "CgkIiYq2_50FEAIQCQ"; // <GPGSID>
        public const string achievement_angel_of_light = "CgkIiYq2_50FEAIQBg"; // <GPGSID>
        public const string achievement_into_the_fire = "CgkIiYq2_50FEAIQBA"; // <GPGSID>
        public const string achievement_the_hidden_forest = "CgkIiYq2_50FEAIQBQ"; // <GPGSID>
        public const string achievement_the_ghost_baron = "CgkIiYq2_50FEAIQBw"; // <GPGSID>

}

